"""empty message

Revision ID: d2eb17436279
Revises: 0248b0a03c29
Create Date: 2018-02-11 14:59:53.915322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2eb17436279'
down_revision = '0248b0a03c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_file_full_loc', sa.String(length=1024), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('enabled_flag', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('salary_number', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salary_number')
    op.drop_column('user', 'role')
    op.drop_column('user', 'password')
    op.drop_column('user', 'enabled_flag')
    op.drop_column('user', 'email')
    op.drop_column('user', 'created_at')
    op.drop_table('request')
    # ### end Alembic commands ###
